const express=require('express');const http=require('http');const cors=require('cors');const{Server}=require('socket.io');
const app=express();app.use(cors());app.get('/health',(_q,s)=>s.json({ok:true,service:'game-server'}));const server=http.createServer(app);
const io=new Server(server,{cors:{origin:process.env.CLIENT_ORIGIN||'*',methods:['GET','POST']}});const rooms=new Map();const MAX={ttt:2,ludo:4,connect4:2,battleship:2},COLORS=['red','blue','green','yellow'],SHIP=[5,4,3,3,2],empty=n=>Array(n).fill(null),rid=x=>String(x||'').trim().toUpperCase(),name=(x,d)=>String(x||d).trim().slice(0,20)||d;
const tttWin=b=>{for(const[a,c,d]of[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]])if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return null};
function room(id,game){const r={id,game,players:[],status:'waiting',winner:null,messages:[],round:1,scores:[],advanceTimer:null};if(game==='ttt')Object.assign(r,{board:empty(9),turn:'X',draw:false});if(game==='connect4')Object.assign(r,{board:empty(42),turn:0,draw:false});if(game==='battleship')r.turn=0;if(game==='ludo')Object.assign(r,{turn:0,dice:null,rolledBy:null});return r}
const player=(r,id)=>r.players.find(p=>p.id===id), players=r=>r.players.map(p=>({id:p.id,name:p.name,slot:p.slot,color:p.color,symbol:p.symbol}));
function state(r,id){const c={roomId:r.id,game:r.game,status:r.status,winner:r.winner,players:players(r),maxPlayers:MAX[r.game],round:r.round,scores:r.scores};if(r.game==='ttt'||r.game==='connect4')return{...c,board:r.board,currentTurn:r.turn,draw:r.draw};if(r.game==='ludo')return{...c,currentTurn:r.turn,dice:r.dice,rolledBy:r.rolledBy,tokens:r.players.map(p=>({id:p.id,color:p.color,tokens:p.tokens}))};const me=player(r,id),op=r.players.find(p=>p.id!==id);return{...c,currentTurn:r.turn,ready:!!me?.ready,opponentReady:!!op?.ready,ownShips:me?.ships||[],ownShots:me?.shots||[],incomingShots:me?.incomingShots||[],opponentShots:op?.shots?.map(s=>({index:s.index,hit:s.hit}))||[]}}
function broadcast(r){r.players.forEach(p=>io.to(p.id).emit('game-state',state(r,p.id)))}
function finish(r,winnerSlot=null){r.winner=Number.isInteger(winnerSlot)?winnerSlot:null;r.status='finished';if(Number.isInteger(winnerSlot))r.scores[winnerSlot]=(r.scores[winnerSlot]||0)+1;broadcast(r);clearTimeout(r.advanceTimer);r.advanceTimer=setTimeout(()=>{if(rooms.get(r.id)!==r||r.players.length<2)return;reset(r);broadcast(r)},4000)}
function reset(r){r.winner=null;r.round+=1;r.status=r.game==='battleship'?'waiting':'playing';if(r.game==='ttt')Object.assign(r,{board:empty(9),turn:'X',draw:false});if(r.game==='connect4')Object.assign(r,{board:empty(42),turn:0,draw:false});if(r.game==='ludo')Object.assign(r,{turn:0,dice:null,rolledBy:null});r.players.forEach(p=>{if(r.game==='ludo')p.tokens=[-1,-1,-1,-1];if(r.game==='battleship'){p.ships=[];p.shots=[];p.incomingShots=[];p.ready=false}})}
function cells(s){return s.flatMap(x=>x.cells)}
function validShips(s){if(!Array.isArray(s)||s.length!==5)return false;const used=new Set();for(let i=0;i<5;i++){const x=s[i];if(!x||!Array.isArray(x.cells)||x.cells.length!==SHIP[i])return false;for(const n of x.cells){if(!Number.isInteger(n)||n<0||n>=100||used.has(n))return false;used.add(n)}const rs=x.cells.map(n=>Math.floor(n/10)),cs=x.cells.map(n=>n%10),sameR=rs.every(v=>v===rs[0]),sameC=cs.every(v=>v===cs[0]);if(!sameR&&!sameC)return false;const a=(sameR?cs:rs).slice().sort((a,b)=>a-b);for(let j=1;j<a.length;j++)if(a[j]!==a[j-1]+1)return false}return true}
const lg=(slot,pos)=>pos<0||pos>=52?null:(slot*13+pos)%52,can=(p,t,d)=>Number.isInteger(d)&&d>0&&t!==56&&(t===-1?d===6:t+d<=56);
function c4(r,p,a,x){if(r.status!=='playing'||r.turn!==p.slot||a!=='drop')return;const col=Number(x.col);if(!Number.isInteger(col)||col<0||col>6)return;let placed=false;for(let row=5;row>=0;row--){const i=row*7+col;if(r.board[i]===null){r.board[i]=p.slot;placed=true;break}}if(!placed)return;const b=r.board,s=p.slot;for(let row=0;row<6;row++)for(let col2=0;col2<7;col2++)if(b[row*7+col2]===s)for(const[dr,dc]of[[1,0],[0,1],[1,1],[1,-1]]){let n=1;for(let k=1;k<4;k++){const rr=row+dr*k,cc=col2+dc*k;if(rr>=0&&rr<6&&cc>=0&&cc<7&&b[rr*7+cc]===s)n++;else break}if(n>=4){finish(r,s);return}}if(b.every(Boolean)){r.draw=true;finish(r,null)}else r.turn=1-r.turn}
function ludo(r,p,a,x){if(r.status!=='playing'||r.turn!==p.slot||r.winner!==null)return;if(a==='roll'){if(r.dice!==null)return;r.dice=1+Math.floor(Math.random()*6);r.rolledBy=p.slot;if(!p.tokens.some(t=>can(p,t,r.dice))){r.dice=r.rolledBy=null;r.turn=(r.turn+1)%r.players.length}return}if(a!=='move'||r.rolledBy!==p.slot)return;const i=Number(x.token),d=r.dice;if(!Number.isInteger(i)||i<0||i>3||!can(p,p.tokens[i],d))return;let n=p.tokens[i];n=n===-1?0:n+d;p.tokens[i]=n;const g=lg(p.slot,n);if(g!==null&&n<52)for(const o of r.players)if(o.id!==p.id)o.tokens=o.tokens.map(v=>v>=0&&v<52&&lg(o.slot,v)===g&&g%13!==0?-1:v);if(p.tokens.every(v=>v===56)){r.dice=r.rolledBy=null;finish(r,p.slot);return}const extra=d===6;r.dice=r.rolledBy=null;if(!extra)r.turn=(r.turn+1)%r.players.length}
function battle(r,p,a,x){if(a==='place-ships'&&r.status==='waiting'){if(!validShips(x.ships))return;p.ships=x.ships.map(s=>({cells:s.cells.slice()}));p.ready=true;if(r.players.length===2&&r.players.every(v=>v.ready))r.status='playing';return}if(r.status!=='playing'||a!=='fire'||r.turn!==p.slot)return;const o=r.players.find(v=>v.id!==p.id),i=Number(x.index);if(!o||!Number.isInteger(i)||i<0||i>=100||p.shots.some(s=>s.index===i))return;const hit=cells(o.ships).includes(i);p.shots.push({index:i,hit});o.incomingShots.push({index:i,hit});if(cells(o.ships).every(n=>p.shots.some(s=>s.index===n&&s.hit))){finish(r,p.slot)}else r.turn=o.slot}
io.on('connection',s=>{s.on('createRoom',({roomId,name:n,game='ttt'})=>{const id=rid(roomId);if(!/^[A-Z0-9]{4,8}$/.test(id)||!MAX[game])return s.emit('errorMessage','Invalid room or game.');if(rooms.has(id))return s.emit('errorMessage','That room already exists.');const r=room(id,game),p={id:s.id,name:name(n,'Player 1'),slot:0,color:COLORS[0],symbol:'X',tokens:game==='ludo'?[-1,-1,-1,-1]:undefined,ships:[],shots:[],incomingShots:[],ready:false};r.players.push(p);r.scores[0]=0;rooms.set(id,r);s.join(id);s.emit('roomCreated',{roomId:id,game,slot:0,color:p.color,symbol:p.symbol});broadcast(r)});
s.on('joinRoom',({roomId,name:n,game})=>{const id=rid(roomId),r=rooms.get(id);if(!r)return s.emit('errorMessage','Room not found.');if(game&&game!==r.game)return s.emit('errorMessage','Wrong game for this room.');if(r.players.length>=MAX[r.game])return s.emit('errorMessage','Room is full.');const slot=r.players.length,p={id:s.id,name:name(n,'Player '+(slot+1)),slot,color:COLORS[slot],symbol:slot?'O':'X',tokens:r.game==='ludo'?[-1,-1,-1,-1]:undefined,ships:[],shots:[],incomingShots:[],ready:false};r.players.push(p);r.scores[slot]=0;s.join(id);if(r.players.length>=2&&r.game!=='battleship')r.status='playing';s.emit('roomJoined',{roomId:id,game:r.game,slot,color:p.color,symbol:p.symbol});broadcast(r)});
s.on('make-move',({roomId,index})=>{const r=rooms.get(rid(roomId)),p=r&&player(r,s.id);if(!r||r.game!=='ttt'||r.status!=='playing'||!p||p.symbol!==r.turn||!Number.isInteger(index)||index<0||index>8||r.board[index])return;r.board[index]=p.symbol;const w=tttWin(r.board);if(w){finish(r,p.slot)}else if(r.board.every(Boolean)){r.draw=true;finish(r,null)}else {r.turn=r.turn==='X'?'O':'X';broadcast(r)}});
s.on('game-action',({roomId,action,payload={}})=>{const r=rooms.get(rid(roomId)),p=r&&player(r,s.id);if(!r||!p)return;if(r.game==='connect4')c4(r,p,action,payload);if(r.game==='ludo')ludo(r,p,action,payload);if(r.game==='battleship')battle(r,p,action,payload);broadcast(r)});
s.on('rematch',({roomId})=>{const r=rooms.get(rid(roomId));if(!r||r.players.length<2)return;clearTimeout(r.advanceTimer);reset(r);broadcast(r)});
s.on('chat-message',({roomId,text:msg})=>{const r=rooms.get(rid(roomId)),p=r&&player(r,s.id),m=String(msg||'').trim().slice(0,300);if(!r||!p||!m)return;const x={id:Date.now()+Math.random(),name:p.name,color:p.color,text:m,at:new Date().toISOString()};r.messages.push(x);if(r.messages.length>50)r.messages.shift();io.to(r.id).emit('chat-message',x)});
s.on('voice-signal',({roomId,targetId,data})=>{const r=rooms.get(rid(roomId));if(r&&player(r,s.id)&&player(r,targetId))io.to(targetId).emit('voice-signal',{fromId:s.id,data})});
s.on('disconnect',()=>{for(const r of rooms.values()){if(!player(r,s.id))continue;r.players=r.players.filter(p=>p.id!==s.id);if(!r.players.length){clearTimeout(r.advanceTimer);rooms.delete(r.id);return}r.status='waiting';r.winner=null;r.round=1;r.scores=[];clearTimeout(r.advanceTimer);if(r.game==='ludo'){r.turn=0;r.dice=r.rolledBy=null;r.players.forEach((p,i)=>{p.slot=i;p.color=COLORS[i];p.tokens=[-1,-1,-1,-1]})}if(r.game==='ttt'){r.board=empty(9);r.turn='X';r.draw=false}if(r.game==='connect4'){r.board=empty(42);r.turn=0;r.draw=false}io.to(r.id).emit('playerLeft');broadcast(r);return}})});
const PORT=Number(process.env.PORT)||5000;server.listen(PORT,()=>console.log('Game server listening on '+PORT));